### ISSUE TITLE
Missing author information in `post.hbs`

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/London#5] opened 2019-01-11 06:33 UTC
From the forum: https://forum.ghost.org/t/author-tab-missing-on-london-theme/4961

Not sure if intentional, but the author information per post is missing. There is a comment that describes the different usage for single and multiple author usage, but the partials are also missing: 

![image](https://user-images.githubusercontent.com/8037602/51017099-54eb3a80-15a5-11e9-99ac-33dd9ab3132f.png)

**Comment by daviddarnes** [comment] 2019-07-30 12:10
@AileenCGN following up on this, I'm anticipating this is by design. Is there another theme we could link to for the person on the forums to refer to?

Going to close this for now, can reopen if I'm wrong

**Closed by daviddarnes** 2019-07-30 12:10 UTC
Labels: bug
